site_name: Feinstaubsensor der TBS1
repo_url: https://github.com/tbs1-bo/luftdaten.tbs1.de/docs

pages:
  - Technische Dokumentation: index.md

#theme: mkdocs
theme: readthedocs

# there is special handling of extra.css
# ignoring this
extra_css: []
