---
- hosts: luftsensor_deploy
  vars:
    www_dest: /var/www/feinstaub
    repo_dest: /home/administrator/proj/luftdaten.tbs1.de
    python_venv: /home/administrator/proj/luftdaten.tbs1.de-ve
    cur_val_rend: '{{ repo_dest }}/current_values_render'

  tasks:
  
  - name: create target directory in web root
    file:
      state: directory
      owner: administrator
      group: www-data
      path: '{{ www_dest }}'
      
  - name: copying files into web dir
    copy:
      src: current_values_render/
      dest: '{{ www_dest }}'
      group: www-data

  - name: update/checkout git repo
    git:
      repo: 'https://github.com/tbs1-bo/luftdaten.tbs1.de.git'
      dest: '{{ repo_dest }}'

  - name: install dependency paho-mqtt
    pip:
      name: paho-mqtt
      virtualenv: '{{ python_venv }}'
      virtualenv_python: python3
      
  - name: create cronjob
    cron:
      name: feinstaub_render_page
      minute: '*'
      job: '{{ python_venv }}/bin/python {{ cur_val_rend }}/feinstaub_render.py --template {{ cur_val_rend }}/current_values.tpl.html --target {{ www_dest }}/index.html'
