---
- hosts: luftsensor_deploy
  vars:
    # TODO adapt these to the correct location
    www_dest: /var/www/feinstaub
    repo_dest: /home/administrator/proj/luftdaten.tbs1.de
  tasks:
  
  - name: create target directory in web root
    file:
      state: directory
      owner: administrator
      group: www-data
      path: '{{ www_dest }}'

  #- name: Copy files into place
  #  copy:
  #    src: current_values_render/
  #    # TODO adapt this to correct location
  #    dest: {{ www_dest }}

  - name: update/checkout git repo
    git:
      repo: 'https://github.com/tbs1-bo/luftdaten.tbs1.de.git'
      dest: '{{ repo_dest }}'

  - name: create cronjob
    cron:
      name: feinstaub_render_page
      minute: '*'
      job: 'cd /home/administrator/proj/luftdaten.tbs1.de/current_values_render/ && /home/administrator/proj/feinstaub-json-mqtt-bridge-ve/bin/python feinstaub_render.py'
      # job: echo
      
